"""
yamlemit.py — minimal deterministic YAML emitter (no third-party dependency).

Supports the shapes used by the cell/router spec library: dicts (insertion
order preserved), lists, str (multiline via literal block scalars), int, float,
bool, None.  Output is stable so the generated YAML is diff-friendly.
"""
from __future__ import annotations

from typing import Any

_BANNER = "# GENERATED by stm32switch — edit the Python spec, not this file.\n"


def _needs_quote(s: str) -> bool:
    if s == "":
        return True
    if s[0] in "!&*?|>%@`\"'#,[]{}:-" or s[-1] in " :":
        return True
    if any(c in s for c in (": ", " #")) or s.strip() != s:
        return True
    if s.lower() in ("true", "false", "null", "yes", "no", "~"):
        return True
    return False


def _scalar(v: Any) -> str:
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    s = str(v)
    if _needs_quote(s):
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return s


def _emit(obj: Any, indent: int, out: list[str]) -> None:
    pad = "  " * indent
    if isinstance(obj, dict):
        if not obj:
            out.append(pad + "{}")
            return
        for k, v in obj.items():
            key = _scalar(k)
            if isinstance(v, dict) and v:
                out.append(f"{pad}{key}:")
                _emit(v, indent + 1, out)
            elif isinstance(v, (list, tuple)) and v:
                out.append(f"{pad}{key}:")
                _emit(list(v), indent + 1, out)
            elif isinstance(v, str) and "\n" in v:
                out.append(f"{pad}{key}: |")
                for line in v.splitlines():
                    out.append(f"{pad}  {line}")
            else:
                out.append(f"{pad}{key}: {_scalar(v) if not isinstance(v,(list,tuple,dict)) else '[]' if not v else _scalar(v)}")
    elif isinstance(obj, (list, tuple)):
        if not obj:
            out.append(pad + "[]")
            return
        for item in obj:
            if isinstance(item, dict) and item:
                # first key inline after '- ', rest indented
                items = list(item.items())
                first_k, first_v = items[0]
                if isinstance(first_v, (dict, list, tuple)) or (isinstance(first_v, str) and "\n" in first_v):
                    out.append(f"{pad}-")
                    _emit(item, indent + 1, out)
                else:
                    out.append(f"{pad}- {_scalar(first_k)}: {_scalar(first_v)}")
                    rest = dict(items[1:])
                    if rest:
                        _emit(rest, indent + 1, out)
            elif isinstance(item, (list, tuple)):
                out.append(f"{pad}-")
                _emit(list(item), indent + 1, out)
            elif isinstance(item, str) and "\n" in item:
                out.append(f"{pad}- |")
                for line in item.splitlines():
                    out.append(f"{pad}  {line}")
            else:
                out.append(f"{pad}- {_scalar(item)}")
    else:
        out.append(pad + _scalar(obj))


def dumps(obj: Any) -> str:
    out: list[str] = []
    _emit(obj, 0, out)
    return _BANNER + "\n".join(out) + "\n"
